### ISSUE TITLE
Can't start baking process

### ISSUE THREAD

**Issue by NazzarenoGiannelli** [Shahzod114/Blender-BakeLab2#1]
On my home pc with 2.82 I have no issues with your addon (and it's really awesome!), but at my studio workstation with almost identical settings and same Blender version I get this error:
```
Traceback (most recent call last):
  File "C:\Users\BoxxApexx1\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\Blender-BakeLab2-master\bakelab_bake.py", line 808, in modal
    result = next(self.BakeCrt)
  File "C:\Users\BoxxApexx1\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\Blender-BakeLab2-master\bakelab_bake.py", line 655, in Bake
    bake_image = self.PrepareImage(context, map, obj, obj.name)
  File "C:\Users\BoxxApexx1\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\Blender-BakeLab2-master\bakelab_bake.py", line 427, in PrepareImage
    bake_image.colorspace_settings.name = map.color_space
TypeError: bpy_struct: item.attr = val: enum "Non-Color" not found in ('BT.1886 EOTF', 'Filmic Log Encoding', 'Linear', 'Non-Colour Data', 'sRGB EOTF')

location: <unknown location>:-1
```
I was trying to find the issue in the bakelab_bake.py, but I wasn't able to.

**Comment by Shahzod114** [comment]
Hello,
Can you send me screenshot of your bake setup?


сб, 29 февр. 2020 г., 14:25 Nazzareno Giannelli <notifications@github.com>:

**Comment by NazzarenoGiannelli** [comment]
Simple Suzanne, random channel added to the bake list with default settings
![Screenshot_2](https://user-images.githubusercontent.com/13347022/75605938-15a0e580-5ae8-11ea-95a9-62829af02bfe.jpg)

After hitting Bake
![Screenshot_3](https://user-images.githubusercontent.com/13347022/75605941-176aa900-5ae8-11ea-8d5f-c4b65fab2f9a.jpg)
![Screenshot_4](https://user-images.githubusercontent.com/13347022/75605939-16397c00-5ae8-11ea-82ba-ca5a08b911d1.jpg)

**Comment by Shahzod114** [comment]
I just fixed it on github, but i cannot test, because everything works for
me. Can you test it?

сб, 29 февр. 2020 г., 15:40 Nazzareno Giannelli <notifications@github.com>:

**Comment by NazzarenoGiannelli** [comment]
All good now!
Thank you very much for the quick fix!
I am gonna buy it on Gumroad for sure! It's gonna save me so much time!
Thanks again for this awesome tool
