### ISSUE TITLE
baking is stuck forever

### ISSUE THREAD

**Issue by Willie2020** [Shahzod114/Blender-BakeLab2#13]
[
![issuue](https://user-images.githubusercontent.com/36770450/113605673-7fb68300-9636-11eb-9a05-647b6b27c283.JPG)
](url)

I tried baking multiple items and now it got suck even after saving the file

**Comment by joshua-whitney** [comment]
Same problem here!

**Comment by claudiomarks** [comment]
Same here, any solutions?

**Comment by BjoernHund** [comment]
@claudiomarks @joshua-whitney I had the same problem. Try to use the diffuse map, instead of the albedo map. That worked for me ;)

**Comment by Gh0StCK** [comment]
I found a manual solution to this problem if you can't solve it as described above.
To reset BakeLab you need:
1. Go to the console (This is called Shift+F4)
2. In it write props = C.scene.BakeLabProps.
3. Then props.bake_state='NONE'
It is all! If the visible window has not changed its status, simply temporarily change the tab to any other one, and then go back to BakeLab.
